# Server Port Configuration
server.port=8080

# Logging Level
logging.level.org.springframework.web=INFO

# Database Connection (Supabase PostgreSQL)
spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://db.bnfycnsebvokulwqennc.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${SUPABASE_DB_USERNAME:postgres}
spring.datasource.password=${SUPABASE_DB_PASSWORD:autotrade@2006}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=${JWT_SECRET:yEb7ZdkG70pJB/t7piMQt+F5Az5gaShtFwHPFmKRk6yoAHCBbq6Gm0fue75AP9uqThPdeCu4kEwoMw/1W/wPyA==}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}



